# Generated by Django 5.0.6 on 2024-07-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='book/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book-image')),
                ('edition', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ISBN_number', models.CharField(blank=True, max_length=40, null=True)),
                ('page_number', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('demo_text', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('volume', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('is_published', models.BooleanField()),
                ('reference', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(to='author.author')),
                ('genre', models.ManyToManyField(to='book.genre')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book.publication')),
            ],
        ),
    ]
